migrate(
  (app) => {
    const col = app.findCollectionByNameOrId('propostas')
    if (!col.fields.getByName('modelo_licitacao'))
      col.fields.add(new BoolField({ name: 'modelo_licitacao' }))
    if (!col.fields.getByName('descricao_proposta'))
      col.fields.add(new TextField({ name: 'descricao_proposta' }))
    if (!col.fields.getByName('especificacoes_tecnicas'))
      col.fields.add(new TextField({ name: 'especificacoes_tecnicas' }))
    if (!col.fields.getByName('materiais_utilizados'))
      col.fields.add(new TextField({ name: 'materiais_utilizados' }))
    if (!col.fields.getByName('certificacoes'))
      col.fields.add(new TextField({ name: 'certificacoes' }))
    if (!col.fields.getByName('normas_aplicaveis'))
      col.fields.add(new TextField({ name: 'normas_aplicaveis' }))
    if (!col.fields.getByName('certificacoes_seguranca'))
      col.fields.add(new TextField({ name: 'certificacoes_seguranca' }))
    if (!col.fields.getByName('normas_seguranca'))
      col.fields.add(new TextField({ name: 'normas_seguranca' }))
    if (!col.fields.getByName('cobertura_garantia'))
      col.fields.add(new TextField({ name: 'cobertura_garantia' }))
    if (!col.fields.getByName('assistencia_tecnica_detalhada'))
      col.fields.add(new TextField({ name: 'assistencia_tecnica_detalhada' }))
    if (!col.fields.getByName('criterios_aceitacao'))
      col.fields.add(new TextField({ name: 'criterios_aceitacao' }))
    if (!col.fields.getByName('garantia_acessorios'))
      col.fields.add(new TextField({ name: 'garantia_acessorios' }))
    if (!col.fields.getByName('validade_oferta'))
      col.fields.add(new TextField({ name: 'validade_oferta' }))
    app.save(col)
  },
  (app) => {
    const col = app.findCollectionByNameOrId('propostas')
    col.fields.removeByName('modelo_licitacao')
    col.fields.removeByName('descricao_proposta')
    col.fields.removeByName('especificacoes_tecnicas')
    col.fields.removeByName('materiais_utilizados')
    col.fields.removeByName('certificacoes')
    col.fields.removeByName('normas_aplicaveis')
    col.fields.removeByName('certificacoes_seguranca')
    col.fields.removeByName('normas_seguranca')
    col.fields.removeByName('cobertura_garantia')
    col.fields.removeByName('assistencia_tecnica_detalhada')
    col.fields.removeByName('criterios_aceitacao')
    col.fields.removeByName('garantia_acessorios')
    col.fields.removeByName('validade_oferta')
    app.save(col)
  },
)
